[projects]

  [projects.default]
  contents = [
    "intro",
    "gerenciador_de_pacotes"
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://programandoemjulia.vento.eng.br"

  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "programandoemjulia"
