baseurl = "https://programandoemjulia.vento.eng.br"
DefaultContentLanguage = "pt-br"
title = "Programando em Julia"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Aprenda a programar em Julia"
  mainSections = ["post","posts"]
  math = true
  logo = "img/julia-brasil.svg" # Expecting square dimensions
  favicon = "img/julia.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Paulo Jabardo"
  website = "programandoemjulia.vento.eng.br"
  email = "pjabardo@gmail.com"
 # facebook = "username"
  github = "pjabardo"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
  youtube = "@ProgramandoEmJulia"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
 # vk = "username"
 # paypal = "username"
 # telegram = "username"
 # 500px = "username"
 # codepen = "username"
 # mastodon = "url"
 # kaggle = "username"
 # weibo = "username"
 # slack = "username"
 # medium = "username"
 # discord = "invite code (https://discord.gg/XXXXXXX)"
 # strava = "userid"
 # lastfm = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Informações"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "julia"	
    name = "Julia"
    weight = 2
    
[[menu.main]]
    parent = "julia"
    name = "Julia"
    url = "https://julialang.org"
    weight = 1

[[menu.main]]
    parent = "julia"
    name = "Download"
    url = "https://julialang.org/downloads/"
    weight = 2

[[menu.main]]
    parent = "julia"
    name = "Documentação"
    url = "https://docs.julialang.org"
    weight = 3

[[menu.main]]
    parent = "julia"
    name = "Fórum oficial (Inglês)"
    url = "https://discourse.julialang.org/"
    weight = 4

[[menu.main]]
   name = "Fórum"
   url = "https://groups.google.com/g/programandoemjulia"
   weight=4
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
